name: Publish Package to NuGet.org

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Build
        run: dotnet build ./src/BreakDown.ManagedPdf.sln --configuration Release /p:VersionNumber=${{ github.event.release.tag_name }}

      - name: Test
        run: dotnet test ./src/BreakDown.ManagedPdf.sln --configuration Release --no-build

      - name: Pack
        run: dotnet pack ./src/BreakDown.ManagedPdf.sln --configuration Release --no-build --output ./publish/packaging

      - name: Publish
        run: dotnet nuget push "./publish/packaging/*.nupkg" --api-key ${{secrets.nugetPublishKey}} --source https://api.nuget.org/v3/index.json